### ISSUE TITLE
Request: update (gear) icon

### ISSUE THREAD

**Issue by AkazaRenn** [Timeraa/SteamDeck-Themes#1]
![image](https://github.com/Timeraa/SteamDeck-Themes/assets/8340896/4b8e9280-fdba-49e2-bdce-20fdabc3a3cd)

```css
._2HnVd7wV6yVaTiXfrBe3gq._8sPcK-HDVUh0QbFshamLa._33cHTEP48tEKJZmhg3APLR.Panel {
    display: none;
}
```

I looked into the CEF debugger but only found this thing, it works, but looks quite different from your code, not sure why. If you don't mind, could you please add support for the update icon? Should be easy to trigger if you switch the update channel in settings.
